language: python
os:
  - linux
python:
  - '3.6'
notifications:
  email: false
jobs:
  include:
    - stage: "Install dependencies"
      script: python3 -m venv venv; . venv/bin/activate; pip install -r requirements.txt
