language: python
os:
  - linux
python:
  - '3.6'
notifications:
  email: false
jobs:
  include:
    - stage: "Install dependencies"
      script: pip3 install -r requirements.txt
    - stage: "Tests"
      script: python3 manage.py test
