language: python

os:
  - linux

python:
  - '3.6'

sudo: required

services:
  - postgresql
#  - rabbitmq
#  - docker

notifications:
  email: false

env:
  global:
    DJANGO_SETTINGS_MODULE="benga.test_settings"

before_script:
  - psql -U postgres -c 'create database travis_ci_test;'

script:
  - sudo apt remove python3-numpy python3-scipy
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test
