language: python

os:
  - linux

python:
  - '3.6'

sudo: required

services:
  - postgresql
  - rabbitmq
  - docker

notifications:
  email: false

addons:
  postgresql: "9.6"
  apt:
    update: true
    packages:
    - docker-ce
    - postgresql-9.6
    - postgresql-client-9.6

before_install:
  - docker pull a504082002/benga:dev

before_script:
  - psql -U postgres -c 'create database travis_ci_test;'

script:
  - docker run --env-file env.list \
      a504082002/benga /bin/sh -c "cd /benga; python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py test"
