language: python

os:
  - linux

python:
  - '3.6'

sudo: required

services:
  - postgresql
  - rabbitmq
#  - docker

notifications:
  email: false

env:
  global:
    DJANGO_SETTINGS_MODULE="benga.test_settings"

addons:
  postgresql: "10"
  apt:
    update: true
    packages:
    - postgresql-10
    - postgresql-client-10

jobs:
  include:
    - stage: "Install dependencies"
      script:
        - pip3 install -r requirements.txt --upgrade
    - stage: "Initiate database"
      script:
        - psql -U postgres -c 'create database travis_ci_test;'
        - python3 manage.py makemigrations
        - python3 manage.py migrate
    - stage: "Test"
      script:
        - python3 manage.py test
