# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          PG_HOST: localhost
          PG_USER: circleci

      - image: circleci/postgres:9.6.10-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: benga

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: initiate database
          command: |
            . venv/bin/activate
            python manage.py makemigrations
            python manage.py migrate

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
  test:
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test